// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShevaTahanotNotifier.Database;

#nullable disable

namespace ShevaTahanotNotifier.Migrations
{
    [DbContext(typeof(NotifierContext))]
    [Migration("20260123150214_AddConversations")]
    partial class AddConversations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.BridgeStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsManualRefresh")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BridgeStatuses");
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextStep")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Conversation", (string)null);
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.NotificationProviderConfiguration.BaseNotificationProviderConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.NotificationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationSchedules");
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.NotificationProviderConfiguration.EmailNotificationProviderConfiguration", b =>
                {
                    b.HasBaseType("ShevaTahanotNotifier.Database.Entities.NotificationProviderConfiguration.BaseNotificationProviderConfiguration");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("TEXT");

                    b.ToTable("EmailNotificationProviderConfiguration", (string)null);
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.NotificationProviderConfiguration.TelegramNotificationProviderConfiguration", b =>
                {
                    b.HasBaseType("ShevaTahanotNotifier.Database.Entities.NotificationProviderConfiguration.BaseNotificationProviderConfiguration");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.ToTable("TelegramNotificationProviderConfiguration", (string)null);
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.Conversation", b =>
                {
                    b.HasOne("ShevaTahanotNotifier.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("System.Collections.Generic.Dictionary<string, string>", "ExtraData", b1 =>
                        {
                            b1.Property<Guid>("ConversationId");

                            b1.HasKey("ConversationId");

                            b1.ToTable("Conversation");

                            b1
                                .ToJson("ExtraData")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ConversationId");
                        });

                    b.Navigation("ExtraData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.NotificationProviderConfiguration.BaseNotificationProviderConfiguration", b =>
                {
                    b.HasOne("ShevaTahanotNotifier.Database.Entities.User", "User")
                        .WithOne("Configuration")
                        .HasForeignKey("ShevaTahanotNotifier.Database.Entities.NotificationProviderConfiguration.BaseNotificationProviderConfiguration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.NotificationSchedule", b =>
                {
                    b.HasOne("ShevaTahanotNotifier.Database.Entities.User", "User")
                        .WithMany("NotificationSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShevaTahanotNotifier.Database.Entities.User", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("NotificationSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
